import AuthContextProvider from "@/Context/authContext";
import dynamic from "next/dynamic";
let Navbar = dynamic(() => import("./Components/Navbar"));
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./Components/Footer";
import { ToastContainer } from "react-toastify";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Places : Flavours of Bangalore",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <div style={{ position: "sticky", top: 0 }}>
            <Navbar />
          </div>
          {children}
          <Footer />
          <ToastContainer />
        </AuthContextProvider>
        <script
          type="text/javascript"
          dangerouslySetInnerHTML={{
            __html: `
                  var _gaq = _gaq || [];
                  _gaq.push(['_setAccount', 'G-VGZTHCKFN0']);
                  _gaq.push(['_setDomainName', 'none']);
                  _gaq.push(['_setAllowLinker', 'true']);
                  _gaq.push(['_trackPageview']);

                  (function() {
                  var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
                  ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                  var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
                  })();
  `,
          }}/>
        <script
          async
          src={`https://www.googletagmanager.com/gtag/js?id=G-VGZTHCKFN0`}
        ></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-VGZTHCKFN0');`,
          }}/>
      </body>
    </html>
  );
}
